### PR TITLE
Add collectives and main_collective parameters.

### PR DESCRIPTION
**Pull request by ASCIIDuck**

### CODE REVIEW

**Comment by ASCIIDuck** [comment]
If you re-run the travis build it should pass. The failures after my most recent commit look like they're caused by an ephemeral issue on the the travis side. (also https://travis-ci.org/ASCIIDuck/puppet-mcollective)

**Comment by raphink** [comment]
That looks good thank you. Let's see if the build passes after I've restarted it.

**Comment by ASCIIDuck** [comment]
I'm a little confused as to why travis is failing on the PR with a bundler error while it's not when it runs against my fork of the repos

**Comment by mcanevet** [comment]
@ASCIIDuck thanks

**Pull request merged**
